version: '3.9'

services:

  postgres:
    restart: always
    image: postgres:14.4-alpine3.16
    ports:
      - 5431:5432
    volumes:
      - db-rancho:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rancho
      - POSTGRES_USER=ranchouser
      - POSTGRES_PASSWORD=admin

  django:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DB_NAME=rancho
      - DB_USER=ranchouser
      - DB_PASSWORD=admin
      - DB_HOST=postgres

volumes:
  db-rancho:
