# Generated by Django 3.2.7 on 2021-09-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_G', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_Empadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_servicio', models.IntegerField()),
                ('mes_servicio', models.IntegerField()),
                ('anio_servicio', models.IntegerField()),
                ('tipo_servicio', models.CharField(max_length=254)),
                ('dia_gestacion', models.IntegerField()),
                ('mes_gestacion', models.IntegerField()),
                ('anio_gestacion', models.IntegerField()),
                ('estado_servicio', models.CharField(max_length=254)),
                ('dia_prob_parto', models.IntegerField()),
                ('mes_prob_parto', models.IntegerField()),
                ('anio_prob_parto', models.IntegerField()),
                ('id_toro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_vaca', to='Control_G.ganado')),
                ('vaca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_toro', to='Control_G.ganado')),
            ],
            options={
                'db_table': 'Control_empadre',
            },
        ),
        migrations.CreateModel(
            name='Tacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datalle', models.CharField(max_length=254)),
                ('hallazgo', models.CharField(max_length=254)),
                ('id_empadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Em.control_empadre')),
            ],
            options={
                'db_table': 'Tacto',
            },
        ),
    ]
