# Generated by Django 3.2.7 on 2021-09-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Em', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tacto',
            old_name='datalle',
            new_name='detalle',
        ),
    ]
