# Generated by Django 3.2.7 on 2021-09-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_G', '0003_alter_ganado_id_raza'),
        ('Control_Em', '0002_rename_datalle_tacto_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_empadre',
            name='id_toro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_vaca', to='Control_G.ganado'),
        ),
        migrations.AlterField(
            model_name='control_empadre',
            name='vaca_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_toro', to='Control_G.ganado'),
        ),
    ]
