# Generated by Django 3.2.7 on 2021-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_IMedicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_insumos',
            name='presentacion',
            field=models.FloatField(default=0),
        ),
    ]
