# Generated by Django 3.2.7 on 2021-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_IMedicos', '0002_inventario_insumos_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_insumos',
            name='producto_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
