# Generated by Django 3.2.7 on 2021-11-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Raza',
            },
        ),
        migrations.CreateModel(
            name='Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
                ('sexo', models.CharField(max_length=254)),
                ('num_economico', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('num_registro', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('num_siniga', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('comentarios', models.CharField(blank=True, max_length=254, null=True)),
                ('fecha_nacimiento', models.CharField(max_length=10, null=True)),
                ('padre', models.CharField(blank=True, max_length=254)),
                ('madre', models.CharField(blank=True, max_length=254)),
                ('fecha_entrada_hato', models.CharField(max_length=10, null=True)),
                ('estado', models.CharField(max_length=254)),
                ('condicion_estadia', models.CharField(max_length=254)),
                ('id_raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_raza', to='Control_Ganado.raza')),
            ],
            options={
                'db_table': 'Ganado',
            },
        ),
    ]
