# Generated by Django 3.2.7 on 2022-08-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Ganado', '0002_auto_20220814_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padre',
            name='ganado',
        ),
        migrations.AlterField(
            model_name='ganado',
            name='madre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Control_Ganado.ganado'),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Control_Ganado.ganado'),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='Madre',
        ),
        migrations.DeleteModel(
            name='Padre',
        ),
    ]
