# Generated by Django 3.2.7 on 2022-08-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Ganado', '0003_auto_20220814_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='ganado',
            name='info_ganado_externo',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Control_Ganado.ganado'),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Control_Ganado.ganado'),
        ),
    ]
