# Generated by Django 3.2.7 on 2021-11-24 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=254)),
                ('mensaje', models.CharField(max_length=254)),
                ('id_user_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emisor', to=settings.AUTH_USER_MODEL)),
                ('id_user_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
