# Generated by Django 3.2.7 on 2021-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Notificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_notificacion',
            name='estado',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
