# Generated by Django 3.2.7 on 2021-09-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_G', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades_Ganado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('numero_casos', models.IntegerField()),
                ('numero_animales', models.IntegerField()),
                ('porcentaje_infectado', models.FloatField()),
                ('dia_detectado', models.IntegerField()),
                ('mes_detectado', models.IntegerField()),
                ('año_detectado', models.IntegerField()),
                ('vacas', models.IntegerField()),
                ('toros', models.IntegerField()),
            ],
            options={
                'db_table': 'Enfermedades',
            },
        ),
        migrations.CreateModel(
            name='Vacas_asociadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_P.enfermedades_ganado')),
                ('id_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_G.ganado')),
            ],
            options={
                'db_table': 'Vacas_asociadas',
            },
        ),
        migrations.CreateModel(
            name='Peso_Ganando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_peso', models.IntegerField()),
                ('mes_peso', models.IntegerField()),
                ('anio_peso', models.IntegerField()),
                ('ganancia_peso_mensual_kilo', models.FloatField()),
                ('ganancia_peso_mensual_porcentaje', models.FloatField()),
                ('estado_vaca', models.CharField(max_length=254)),
                ('peso', models.FloatField()),
                ('id_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_G.ganado')),
            ],
            options={
                'db_table': 'Peso',
            },
        ),
    ]
