# Generated by Django 3.2.7 on 2021-09-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_P', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermedades_ganado',
            old_name='año_detectado',
            new_name='anio_detectado',
        ),
    ]
