# Generated by Django 3.2.7 on 2021-09-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_P', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso_ganando',
            old_name='id_ganado',
            new_name='ganado',
        ),
        migrations.RenameField(
            model_name='vacas_asociadas',
            old_name='id_enfermedad',
            new_name='enfermedad',
        ),
        migrations.RenameField(
            model_name='vacas_asociadas',
            old_name='id_ganado',
            new_name='ganado',
        ),
    ]
