# Generated by Django 3.2.7 on 2021-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_P', '0002_auto_20210919_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso_ganando',
            old_name='ganado',
            new_name='id_ganado',
        ),
        migrations.RenameField(
            model_name='vacas_asociadas',
            old_name='enfermedad',
            new_name='id_enfermedad',
        ),
        migrations.RenameField(
            model_name='vacas_asociadas',
            old_name='ganado',
            new_name='id_ganado',
        ),
    ]
