# Generated by Django 3.2.7 on 2021-09-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_G', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganado',
            name='comentarios',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='num_economico',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='num_registro',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='num_siniga',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
