# Generated by Django 3.2.7 on 2021-09-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_G', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganado',
            name='anio_entrada_hato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='anio_nacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='dia_entrada_hato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='dia_nacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='mes_entrada_hato',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ganado',
            name='mes_nacimiento',
            field=models.IntegerField(),
        ),
    ]
