# Generated by Django 3.2.7 on 2021-09-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_G', '0002_auto_20210917_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ganado',
            old_name='id_raza',
            new_name='raza',
        ),
    ]
