# Generated by Django 3.2.7 on 2021-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_G', '0003_rename_id_raza_ganado_raza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ganado',
            old_name='raza',
            new_name='id_raza',
        ),
    ]
