# Generated by Django 3.2.7 on 2021-09-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_E', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_canastilla', models.IntegerField()),
                ('nombre_toro', models.CharField(max_length=254)),
                ('raza', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('cantidad', models.IntegerField()),
                ('comentario', models.CharField(max_length=254)),
                ('num_termo', models.IntegerField()),
            ],
            options={
                'db_table': 'Inventario_Termo',
            },
        ),
        migrations.CreateModel(
            name='Empadre_Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_E.control_empadre')),
                ('id_inv_termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_T.inventario_termo')),
            ],
            options={
                'db_table': 'Empadre_Termo',
            },
        ),
    ]
