# Generated by Django 3.2.7 on 2021-11-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_Ganado', '0001_initial'),
        ('Control_Empadre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario_termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_canastilla', models.IntegerField()),
                ('raza', models.CharField(max_length=254)),
                ('descripcion', models.CharField(blank=True, max_length=254, null=True)),
                ('cantidad', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=254, null=True)),
                ('num_termo', models.IntegerField()),
                ('id_ganado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Control_Ganado.ganado')),
            ],
            options={
                'db_table': 'Inventario_Termocriogenico',
            },
        ),
        migrations.CreateModel(
            name='Empadre_Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Empadre.control_empadre')),
                ('id_inv_termo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Control_Termocrio.inventario_termo')),
            ],
            options={
                'db_table': 'Empadre_Termocriogenico',
            },
        ),
    ]
