# Generated by Django 3.2.7 on 2021-11-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Termocrio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario_termo',
            name='raza',
        ),
    ]
