# Generated by Django 3.2.7 on 2021-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apellido_paterno', models.CharField(max_length=254)),
                ('apellido_materno', models.CharField(max_length=254)),
                ('usuario', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('roll', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
