# Generated by Django 3.2.7 on 2021-11-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control_Ganado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_Empadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.CharField(max_length=10, null=True)),
                ('tipo_servicio', models.CharField(max_length=254)),
                ('fecha_gestacion', models.CharField(max_length=10, null=True)),
                ('estado_servicio', models.CharField(max_length=254)),
                ('fecha_parto', models.CharField(max_length=10, null=True)),
                ('id_toro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_vaca', to='Control_Ganado.ganado')),
                ('vaca_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_toro', to='Control_Ganado.ganado')),
            ],
            options={
                'db_table': 'Control_empadre',
            },
        ),
        migrations.CreateModel(
            name='Tacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=254)),
                ('hallazgo', models.CharField(max_length=254)),
                ('fecha', models.CharField(max_length=10, null=True)),
                ('id_empadre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Control_Empadre.control_empadre')),
            ],
            options={
                'db_table': 'Tacto',
            },
        ),
    ]
