# Generated by Django 3.2.7 on 2021-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Empadre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_empadre',
            name='fecha_aborto',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
