# Generated by Django 3.2.7 on 2022-08-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_Empadre', '0002_control_empadre_fecha_aborto'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_empadre',
            name='linea_sanguina_embrion',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='control_empadre',
            name='observaciones',
            field=models.TextField(max_length=254, null=True),
        ),
    ]
